# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-UpoTsEQxQGCPW-EkWd6kiS7s0uMUlw
"""

def QuickSort(array, start, end):
    if start >= end:
        return
    pivot = array[start]
    left = start + 1
    right = end
    while left <= right:
        while left <= right and array[left] <= pivot:
            left = left + 1
        while left <= right and array[right] >= pivot:
            right = right - 1
        if left < right:
            array[left], array[right] = array[right], array[left]
    array[start], array[right] = array[right], array[start]
    QuickSort(array, start, right - 1)
    QuickSort(array, right + 1, end)

arr = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
QuickSort(arr, 0, len(arr) - 1)
print("Sorted array:", arr)